# Nota: al declarar variables dentro de un rol, el prefijo debe coincidir con el rol

vsftpd_banner: "-- Welcome to the FTP server of 'sistema.sol'"
vsftpd_root: "/srv/ftp"
vsftpd_max_clients: 15
vsftpd_local_max_rate: 5000000
vsftpd_anon_max_rate: 2000000
vsftpd_idle_timeout: 720

vsftpd_cert_path: "/etc/ssl/certs/example.test.pem"
vsftpd_key_path: "/etc/ssl/private/example.test.key"

ftp_users:
  - { name: 'luis', jailed: true }
  - { name: 'maria', jailed: false }
  - { name: 'miguel', jailed: true }