- name: Instalar vsftpd
  ansible.builtin.apt:
    name: vsftpd
    state: present
    update_cache: true

- name: Crear directorio FTP
  ansible.builtin.file:
    path: /srv/ftp
    state: directory
    owner: root
    group: ftp
    mode: '0755'

# Nota: dentro de un rol ansible resuleve las rutas files y templates por lo que no hace falta especificarlas

- name: Copiar mensaje de entrada
  ansible.builtin.copy:
    src: message.txt
    dest: /srv/ftp/.message
    owner: root
    group: ftp
    mode: '0644'

- name: Configurar vsftpd
  ansible.builtin.template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd.conf
  notify: Reiniciar vsftpd

- name: Asegurar servicio vsftpd activo
  ansible.builtin.service:
    name: vsftpd
    state: started
    enabled: true
